#!/bin/bash
# eggd_somalier_relate 0.0.1
# Generated by dx-app-wizard.

set -euxo pipefail

main() {

    echo "Value of input_file: '${input_file[@]}'"

    # install python packages from included wheels
    # pip install --upgrade pip
    pip install packages/pandas-0.24.2-cp35-cp35m-manylinux1_x86_64.whl

    dx-download-all-inputs

    find ~/in -type f -name "*" -print0 | xargs -0 -I {} mv {} ./

    ls -a

    python3 make_ped.py -a *.somalier

    # Give permission rights
    echo "--------------Change permissions-----------------"
    sudo chmod 777 /usr/bin/somalier


    
    # Now run static binary in resources/usr/bin
    echo "--------------Run Somalier extract-----------------"
    mkdir -p /home/dnanexus/out/html/
    mkdir -p /home/dnanexus/out/pairs_tsv/
    mkdir -p /home/dnanexus/out/samples_tsv/
    mkdir -p /home/dnanexus/out/groups_tsv/

    cd /home/dnanexus/out/
    ls -a
    pwd

    somalier relate --ped /home/dnanexus/*.ped /home/dnanexus/*.somalier

    service docker start

    # Load tabix
    docker load -i somalier_v0_2_12.tar.gz

    docker run -v /home/dnanexus:/data brentp/somalier:v0.2.12 somalier relate --ped data/*.ped /data/*.somalier

    
    ls -a

    mv /home/dnanexus/out/somalier.html /home/dnanexus/out/html/
    mv /home/dnanexus/out/somalier.pairs.tsv /home/dnanexus/out/pairs_tsv/
    mv /home/dnanexus/out/somalier.samples.tsv /home/dnanexus/out/samples_tsv/
    mv /home/dnanexus/out/somalier.groups.tsv /home/dnanexus/out/groups_tsv/

    ls -a /home/dnanexus/out/html
    ls -a /home/dnanexus/out/pairs_tsv
    ls -a /home/dnanexus/out/samples_tsv
    ls -a /home/dnanexus/out/groups_tsv
    ls -a /home/dnanexus/out/

    dx-upload-all-outputs
}
